import { Artwork } from './types';

export const INITIAL_ARTWORKS: Artwork[] = [
  {
    id: 'art-1',
    title: 'მრავალსახე',
    titleEn: 'Multiface',
    category: 'ხის სულები (WOODSPIRIT)',
    tag: 'ხის სული (WOODSPIRIT)',
    tagEn: 'Woodspirit',
    description: 'უხეში ქერქის წიაღიდან გამოხშობილი ზღაპრული სახეები, სადაც ყოველი ნაოჭი და ხაზი ტყის უძველეს ისტორიას ყვება.',
    descriptionEn: 'Fairy-tale faces carved from rough bark, where every wrinkle and line tells an ancient story of the forest.',
    image: '/images/ws-4face.png',
    dimensions: '35 X 10 სმ',
    dimensionsEn: '35 X 10 cm',
    materials: ['ალუბლის ხე'],
    materialsEn: ['Cherry Wood'],
    stock: 1,
    createdAt: '2026',
    price: '0.00₾'
  },
  {
    id: 'art-2',
    title: 'ბრძენი',
    titleEn: 'The Wise One',
    category: 'ხის სულები (WOODSPIRIT)',
    tag: 'ხის სული (WOODSPIRIT)',
    tagEn: 'Woodspirit',
    description: 'მისტიკური ტყის სული, რომელიც თითქოს ქერქიდან მოგვმართავს. სიყვარულით და ხის ბუნებრივი ხასიათის პატივისცემით შექმნილი სიმბოლო, რომელიც თქვენს სახლში სიმშვიდეს შემოიტანს.',
    descriptionEn: 'A mystical forest spirit carved from bark, created with reverence for natural wood to bring tranquility to your home.',
    image: '/images/ws-beard.png',
    dimensions: '35 X 8 სმ',
    dimensionsEn: '35 X 8 cm',
    materials: ['გარგარის ხე'],
    materialsEn: ['Apricot Wood'],
    stock: 2,
    createdAt: '2025',
    price: '0.00₾'
  },
  {
    id: 'art-3',
    title: 'ხინკლის კედლის საათი',
    titleEn: 'Khinkali Wall Clock',
    category: 'ესთეტიკური & პრაქტიკული',
    tag: 'ესთეტიკური ნივთი',
    tagEn: 'Aesthetic Item',
    description: 'ხინკლის ფორმის ორიგინალური კედლის საათი. მხიარული და კრეატიული აქსესუარი, რომელიც ნებისმიერ ინტერიერს გაალამაზებს.',
    descriptionEn: 'Original wall clock shaped like a traditional Khinkali. A joyful, creative piece for any interior.',
    image: '/images/khinkali-clock.png',
    dimensions: '30 X 30 სმ',
    dimensionsEn: '30 X 30 cm',
    materials: ['ხის დაფა'],
    materialsEn: ['Wood Board'],
    stock: 4,
    createdAt: '2025-06-20',
    price: '0.00₾'
  },
  {
    id: 'art-4',
    title: 'სასანთლე ანათე',
    titleEn: 'Anate Candleholder',
    category: 'ესთეტიკური & პრაქტიკული',
    tag: 'ესთეტიკური ნივთი',
    tagEn: 'Aesthetic Item',
    description: 'ხელით დამუშავებული ატმოსფერული სასანთლე "ანათე". გამოირჩევა ნატურალური ფაქტურით, საიდანაც ნაზად კრთის სანთლის შუქი, ქმნის თბილ ჩრდილებს.',
    descriptionEn: 'Hand-crafted atmospheric candleholder "Anate", bringing soft light and warm shadows into your room.',
    image: '/images/anate-white.png',
    dimensions: '8 X 8 სმ',
    dimensionsEn: '8 X 8 cm',
    materials: ['ცაცხვის ხე'],
    materialsEn: ['Linden Wood'],
    stock: 3,
    createdAt: '2025-06-15',
    price: '0.00₾'
  },
  {
    id: 'art-5',
    title: 'ხის სანათი / სასანთლე',
    titleEn: 'Wooden Lamp / Candleholder',
    category: 'ესთეტიკური & პრაქტიკული',
    tag: 'ესთეტიკური ნივთი',
    tagEn: 'Aesthetic Item',
    description: 'სათუთად გამოთლილი ხის სანათი-სასანთლე, რომელიც თბილი ალითა და ნატურალური ფაქტურით მყუდრო საღამოსთვის იდეალურ ატმოსფეროს ქმნის.',
    descriptionEn: 'Delicately carved wooden light holder that creates a cozy ambiance with natural timber texture.',
    image: '/images/xe-candle-white.png',
    dimensions: '10 X 8 სმ',
    dimensionsEn: '10 X 8 cm',
    materials: ['ქლიავის ხე'],
    materialsEn: ['Plum Wood'],
    stock: 3,
    createdAt: '2025-06-12',
    price: '0.00₾'
  },
  {
    id: 'art-6',
    title: 'ღვინის კოსმოსური დამჭერი',
    titleEn: 'Cosmic Wine Holder',
    category: 'ესთეტიკური & პრაქტიკული',
    tag: 'ესთეტიკური ნივთი',
    tagEn: 'Aesthetic Item',
    description: 'ფიზიკის კანონებისა და ხის ოსტატობის საოცარი ნაზავი. აღნიშნული დამჭერი ინარჩუნებს სიმძიმის ცენტრს და ჰაერში აბალანსებს ბოთლს.',
    descriptionEn: 'A blend of physics and woodcraft that balances a bottle gracefully in mid-air using gravity.',
    image: '/images/wineholder.png',
    dimensions: '45 X 42 სმ',
    dimensionsEn: '45 X 42 cm',
    materials: ['ალუბლის ხე'],
    materialsEn: ['Cherry Wood'],
    stock: 6,
    createdAt: '2025-06-16',
    price: '0.00₾'
  },
  {
    id: 'art-7',
    title: 'ქართული ორნამენტული საათი',
    titleEn: 'Georgian Ornamental Clock',
    category: 'ესთეტიკური & პრაქტიკული',
    tag: 'ესთეტიკური ნივთი',
    tagEn: 'Aesthetic Item',
    description: 'ხელით ამოკვეთილი ქართული ორნამენტებითა და ბორჯღალით დამზადებული კედლის ხის საათი.',
    descriptionEn: 'Hand-carved wooden wall clock decorated with traditional Georgian ornaments and Borjgali.',
    image: '/images/geo-clock.png',
    dimensions: '75 X 27 სმ',
    dimensionsEn: '75 X 27 cm',
    materials: ['კაკლის ხე'],
    materialsEn: ['Walnut Wood'],
    stock: 2,
    createdAt: '2025-06-22',
    price: '0.00₾'
  }
];

export const TRANSLATIONS = {
  ka: {
    heroTitle: 'ხის ნამუშევრების საგვარეულო Atelier',
    heroSubtitle: 'ეკოლოგიურად სუფთა მეთოდებით, გააზრებული შრომითა და ექსკლუზიური ქართული ხის ჯიშებით დამზადებული ნამუშევრები.',
    all: 'ყველა ნამუშევარი',
    woodspirits: 'ხის სულები (WOODSPIRIT)',
    aesthetic: 'ესთეტიკური & პრაქტიკული',
    faces: 'ემოციური სახეები',
    aboutTitle: 'ნელი ხელნაკეთობის ფილოსოფია',
    aboutText: 'ჩვენ ვქმნით ხის საავტორო ნივთებს, ძვირფასი და გადარჩენილი ქართული ხის ჯიშებისგან. თითოეულ ნამუშევარს აქვს საკუთარი ისტორია, ფაქტურა და ხის ბუნებრივი ხაზები.',
    customOrderTitle: 'ინდივიდუალური ხის შეკვეთა',
    customOrderSubtitle: 'გაქვთ საკუთარი ესკიზი ან გსურთ ავეჯის, დაფის თუ ჯამის უნიკალურ ზომებში დამზადება? მოგვწერეთ დეტალები.',
    filterTitle: 'ხის კატეგორიები',
    materialsLabel: 'მასალები',
    dimensionsLabel: 'ზომები',
    storyLabel: 'ნამუშევრის ისტორია',
    addToWishlist: 'რჩეულებში დამატება',
    removeFromWishlist: 'რჩეულებიდან ამოღება',
    priceLabel: 'ფასი',
    enquireBtn: 'შეკვეთა',
    orderFormName: 'თქვენი სახელი',
    orderFormEmail: 'ელ.ფოსტა',
    orderFormDesc: 'სასურველი ხის ნივთის აღწერა...',
    orderFormDimensions: 'სასურველი ზომები ან ფართობი',
    orderFormMaterial: 'ხის მასალის უპირატესობა',
    orderFormColors: 'ტონალობა / დასრულება',
    orderFormSubmit: 'გააგზავნეთ შეკვეთის მოთხოვნა',
    orderEstimateResult: 'შეკვეთის მონახაზი',
    orderSubmittedSuccess: 'ინდივიდუალური შეკვეთის მოთხოვნა შენახულია! ოსტატი მალე დაგიკავშირდებათ დიზაინის განსახილველად.',
    searchPlaceholder: 'ძიება: მასალა, დასახელება...',
    sortByPriceAsc: 'ფასი: ზრდადობით',
    sortByPriceDesc: 'ფასი: კლებადობით',
    sortByViews: 'პოპულარობა',
    sortByLatest: 'ახალი დამატებული',
    sortLabel: 'სორტირება:',
    navHome: 'მთავარი',
    navGallery: 'გალერეა',
    navCommission: 'ინდივიდუალური შეკვეთა',
    featuredCreations: 'გამორჩეული ხელნაკეთობები',
    exploreMoreBtn: 'ყველა ნამუშევრის ნახვა',
    totalArtworks: 'ნამუშევარი',
    processTitle: 'დამზადების პროცესი',
    process1Title: '1. მასალის შერჩევა',
    process1Desc: 'ვიყენებთ მხოლოდ ქარისგან წაქცეული ან გადარჩენილი ბუნებრივი ხის მორებს.',
    process2Title: '2. ხელით გამოთლა / მუშაობა',
    process2Desc: 'ტრადიციული ხორხითა და სატეხებით ვამუშავებთ და ვანიჭებთ უნიკალურ ფორმას.',
    process3Title: '3. ეკოლოგიური დაცვა',
    process3Desc: 'ვჟღენთთ სელის ბუნებრივი ზეთითა და ფუტკრის ცვილით სრული სიმტკიცისთვის.',
    galleryIntro: 'ჩვენი სრული კატალოგი. თითოეული ნამუშევარი იქმნება ერთადერთ ეგზემპლარად.'
  },
  en: {
    heroTitle: 'Artisanal Wooden Masterpieces',
    heroSubtitle: 'Heirloom creations designed and hand-carved with ancient Georgian techniques and sustainably salvaged wild timber.',
    all: 'All Crafts',
    woodspirits: 'Woodspirits (WOODSPIRIT)',
    aesthetic: 'Aesthetic & Practical',
    faces: 'Emotional Faces',
    aboutTitle: 'The Slow Wood Creed',
    aboutText: 'We craft signature wooden statement pieces from exquisite salvaged Georgian timber.',
    customOrderTitle: 'Custom Wooden Commission Request',
    customOrderSubtitle: 'Do you have a custom design script or specified size requirements in mind?',
    filterTitle: 'Lumber Categories',
    materialsLabel: 'Materials / Timber',
    dimensionsLabel: 'Dimensions',
    storyLabel: 'Woodwork Narrative',
    addToWishlist: 'Add to Wishlist',
    removeFromWishlist: 'Remove from Wishlist',
    priceLabel: 'Price',
    enquireBtn: 'Inquire / Order Piece',
    orderFormName: 'Your Name',
    orderFormEmail: 'Email Address',
    orderFormDesc: 'Describe your vision...',
    orderFormDimensions: 'Target Dimensions',
    orderFormMaterial: 'Timber Preference',
    orderFormColors: 'Shade / Surface Finish',
    orderFormSubmit: 'Submit Custom Request',
    orderEstimateResult: 'Commission Proposal draft',
    orderSubmittedSuccess: 'Your custom wood commission draft has been submitted!',
    searchPlaceholder: 'Search: material, name...',
    sortByPriceAsc: 'Price: Low to High',
    sortByPriceDesc: 'Price: High to Low',
    sortByViews: 'Popularity',
    sortByLatest: 'Fresh Arrivals',
    sortLabel: 'Sort by:',
    navHome: 'Home',
    navGallery: 'Craft Gallery',
    navCommission: 'Custom Commissions',
    featuredCreations: 'Featured Masterpieces',
    exploreMoreBtn: 'Explore Full Gallery',
    totalArtworks: 'Items Available',
    processTitle: 'The Crafting Cycle',
    process1Title: '1. Sourced with honor',
    process1Desc: 'We harvest wood from naturally fallen trunks.',
    process2Title: '2. Sculpted & Turned',
    process2Desc: 'Utilizing specialized manual chisels to shape contours.',
    process3Title: '3. Organic Sealing',
    process3Desc: 'Cured and rubbed with raw flaxseed oil and beeswax.',
    galleryIntro: 'Our complete woodcraft directory.'
  }
};
